; Generated by scripts/generate-legacy-hook.mjs from cleanup-legacy-engine.ps1.
; The UTF-16LE payload is split because bundled NSIS uses a 1024-character string limit.
!define MAVRODPI_LEGACY_SCRIPT_1 "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKAAoAJABjAGkAbQBNAG8AZAB1AGwAZQAgAD0AIABbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBHAGUAdABFAG4AdgBpAHIAbwBuAG0AZQBuAHQAVgBhAHIAaQBhAGIAbABlACgACgAgACAAJwBNAEEAVgBSAE8ARABQAEkAXwBDAEkATQBfAE0ATwBEAFUATABFACcALAAKACAAIAAnAFAAcgBvAGMAZQBzAHMAJwAKACkACgBpAGYAIAAoAAoAIAAgAFsAcwB0AHIAaQBuAGcAXQA6ADoASQBzAE4AdQBsAGwATwByAFcAaABpAHQAZQBTAHAAYQBjAGUAKAAkAGMAaQBtAE0AbwBkAHUAbABlACkAIAAtAG8AcgAKACAAIAAtAG4AbwB0ACAAWwBJAE8ALgBQAGEAdABoAF0AOgA6AEkAcwBQAGEAdABoAFIAbwBvAHQAZQBkACgAJABjAGkAbQBNAG8AZAB1AGwAZQApACAALQBvAHIACgAgACAALQBuAG8AdAAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAYwBpAG0ATQBvAGQAdQBs"
!define MAVRODPI_LEGACY_SCRIPT_2 "AGUAIAAtAFAAYQB0AGgAVAB5AHAAZQAgAEwAZQBhAGYAKQAKACkAIAB7AAoAIAAgAHQAaAByAG8AdwAgACcAVAByAHUAcwB0AGUAZAAgAEMASQBNACAAbQBvAGQAdQBsAGUAIABwAGEAdABoACAAaQBzACAAaQBuAHYAYQBsAGkAZAAuACcACgB9AAoASQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgAC0ATgBhAG0AZQAgACQAYwBpAG0ATQBvAGQAdQBsAGUAIAAtAEYAbwByAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwB0AG8AcAAKAAoAJABlAHgAcABlAGMAdABlAGQAUgBhAHcAIAA9ACAAWwBFAG4AdgBpAHIAbwBuAG0AZQBuAHQAXQA6ADoARwBlAHQARQBuAHYAaQByAG8AbgBtAGUAbgB0AFYAYQByAGkAYQBiAGwAZQAoAAoAIAAgACcATQBBAFYAUgBPAEQAUABJAF8ATABFAEcAQQBDAFkAXwBFAE4ARwBJAE4ARQBfAFAAQQBUAEgAJwAsAAoAIAAgACcAUAByAG8AYwBlAHMAcwAnAAoAKQAKAGkAZgAgACgAWwBzAHQAcgBpAG4AZwBdADoAOgBJAHMATgB1AGwAbABPAHIAVwBoAGkAdABlAFMAcABhAGMAZQAoACQA"
!define MAVRODPI_LEGACY_SCRIPT_3 "ZQB4AHAAZQBjAHQAZQBkAFIAYQB3ACkAKQAgAHsACgAgACAAdABoAHIAbwB3ACAAJwBMAGUAZwBhAGMAeQAgAGUAbgBnAGkAbgBlACAAcABhAHQAaAAgAHcAYQBzACAAbgBvAHQAIABwAHIAbwB2AGkAZABlAGQALgAnAAoAfQAKAAoAJABlAHgAcABlAGMAdABlAGQAIAA9ACAAWwBJAE8ALgBQAGEAdABoAF0AOgA6AEcAZQB0AEYAdQBsAGwAUABhAHQAaAAoACQAZQB4AHAAZQBjAHQAZQBkAFIAYQB3ACkACgBpAGYAIAAoAFsASQBPAC4AUABhAHQAaABdADoAOgBHAGUAdABGAGkAbABlAE4AYQBtAGUAKAAkAGUAeABwAGUAYwB0AGUAZAApACAALQBpAG4AZQAgACcAZwBvAG8AZABiAHkAZQBkAHAAaQAuAGUAeABlACcAKQAgAHsACgAgACAAdABoAHIAbwB3ACAAJwBMAGUAZwBhAGMAeQAgAGUAbgBnAGkAbgBlACAAZgBpAGwAZQAgAG4AYQBtAGUAIABpAHMAIABpAG4AdgBhAGwAaQBkAC4AJwAKAH0ACgAKACQAcAByAG8AZwByAGEAbQBGAGkAbABlAHMAUgBhAHcAIAA9ACAAWwBFAG4AdgBpAHIAbwBuAG0AZQBuAHQAXQA6ADoARwBl"
!define MAVRODPI_LEGACY_SCRIPT_4 "AHQARQBuAHYAaQByAG8AbgBtAGUAbgB0AFYAYQByAGkAYQBiAGwAZQAoACcAUAByAG8AZwByAGEAbQBXADYANAAzADIAJwAsACAAJwBQAHIAbwBjAGUAcwBzACcAKQAKAGkAZgAgACgAWwBzAHQAcgBpAG4AZwBdADoAOgBJAHMATgB1AGwAbABPAHIAVwBoAGkAdABlAFMAcABhAGMAZQAoACQAcAByAG8AZwByAGEAbQBGAGkAbABlAHMAUgBhAHcAKQApACAAewAKACAAIAAkAHAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzAFIAYQB3ACAAPQAgAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEcAZQB0AEYAbwBsAGQAZQByAFAAYQB0AGgAKAAnAFAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzACcAKQAKAH0ACgAkAHAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzACAAPQAgAFsASQBPAC4AUABhAHQAaABdADoAOgBHAGUAdABGAHUAbABsAFAAYQB0AGgAKAAkAHAAcgBvAGcAcgBhAG0ARgBpAGwAZQBzAFIAYQB3ACkALgBUAHIAaQBtAEUAbgBkACgAJwBcACcAKQAgACsAIAAnAFwAJwAKAGkAZgAgACgALQBuAG8AdAAgACQAZQB4AHAAZQBjAHQA"
!define MAVRODPI_LEGACY_SCRIPT_5 "ZQBkAC4AUwB0AGEAcgB0AHMAVwBpAHQAaAAoACQAcAByAG8AZwByAGEAbQBGAGkAbABlAHMALAAgAFsAUwB0AHIAaQBuAGcAQwBvAG0AcABhAHIAaQBzAG8AbgBdADoAOgBPAHIAZABpAG4AYQBsAEkAZwBuAG8AcgBlAEMAYQBzAGUAKQApACAAewAKACAAIAB0AGgAcgBvAHcAIAAnAEwAZQBnAGEAYwB5ACAAZQBuAGcAaQBuAGUAIABpAHMAIABvAHUAdABzAGkAZABlACAAUAByAG8AZwByAGEAbQAgAEYAaQBsAGUAcwAuACcACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABHAGUAdAAtAEUAeABhAGMAdABMAGUAZwBhAGMAeQBQAHIAbwBjAGUAcwBzACAAewAKACAAIABAACgACgAgACAAIAAgAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8AUAByAG8AYwBlAHMAcwAgAC0ARgBpAGwAdABlAHIAIAAiAE4AYQBtAGUAPQAnAGcAbwBvAGQAYgB5AGUAZABwAGkALgBlAHgAZQAnACIAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAdABvAHAAIAB8AAoAIAAgACAAIAAgACAAVwBoAGUAcgBlAC0ATwBi"
!define MAVRODPI_LEGACY_SCRIPT_6 "AGoAZQBjAHQAIAB7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgALQBuAG8AdAAgACQAXwAuAEUAeABlAGMAdQB0AGEAYgBsAGUAUABhAHQAaAApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAkAGYAYQBsAHMAZQAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIABbAEkATwAuAFAAYQB0AGgAXQA6ADoARwBlAHQARgB1AGwAbABQAGEAdABoACgAWwBzAHQAcgBpAG4AZwBdACQAXwAuAEUAeABlAGMAdQB0AGEAYgBsAGUAUABhAHQAaAApAC4ARQBxAHUAYQBsAHMAKAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAZQB4AHAAZQBjAHQAZQBkACwACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABbAFMAdAByAGkAbgBnAEMAbwBtAHAAYQByAGkAcwBvAG4AXQA6ADoATwByAGQAaQBuAGEAbABJAGcAbgBvAHIAZQBDAGEAcwBlAAoAIAAgACAAIAAgACAAIAAgACAAIAApAAoAIAAgACAAIAAgACAAIAAgAH0A"
!define MAVRODPI_LEGACY_SCRIPT_7 "IABjAGEAdABjAGgAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgACQAZgBhAGwAcwBlAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAB9AAoAIAAgACkACgB9AAoACgBmAG8AcgBlAGEAYwBoACAAKAAkAHAAcgBvAGMAZQBzAHMAIABpAG4AIAAoAEcAZQB0AC0ARQB4AGEAYwB0AEwAZQBnAGEAYwB5AFAAcgBvAGMAZQBzAHMAKQApACAAewAKACAAIAAkAHIAZQBzAHUAbAB0ACAAPQAgAEkAbgB2AG8AawBlAC0AQwBpAG0ATQBlAHQAaABvAGQAIABgAAoAIAAgACAAIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAcAByAG8AYwBlAHMAcwAgAGAACgAgACAAIAAgAC0ATQBlAHQAaABvAGQATgBhAG0AZQAgAFQAZQByAG0AaQBuAGEAdABlACAAYAAKACAAIAAgACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwAAoAIAAgAGkAZgAgACgAWwBpAG4AdABdACQAcgBlAHMAdQBsAHQALgBSAGUAdAB1AHIAbgBWAGEAbAB1AGUAIAAtAG4AZQAgADAAKQAgAHsACgAgACAAIAAgAHQAaABy"
!define MAVRODPI_LEGACY_SCRIPT_8 "AG8AdwAgACIATABlAGcAYQBjAHkAIABlAG4AZwBpAG4AZQAgAGMAbwB1AGwAZAAgAG4AbwB0ACAAYgBlACAAcwB0AG8AcABwAGUAZAA6ACAAJAAoACQAcgBlAHMAdQBsAHQALgBSAGUAdAB1AHIAbgBWAGEAbAB1AGUAKQAiAAoAIAAgAH0ACgB9AAoACgAkAGQAZQBhAGQAbABpAG4AZQAgAD0AIABbAEQAYQB0AGUAVABpAG0AZQBdADoAOgBVAHQAYwBOAG8AdwAuAEEAZABkAFMAZQBjAG8AbgBkAHMAKAAxADAAKQAKAGQAbwAgAHsACgAgACAAJAByAGUAbQBhAGkAbgBpAG4AZwAgAD0AIABAACgARwBlAHQALQBFAHgAYQBjAHQATABlAGcAYQBjAHkAUAByAG8AYwBlAHMAcwApAAoAIAAgAGkAZgAgACgAJAByAGUAbQBhAGkAbgBpAG4AZwAuAEMAbwB1AG4AdAAgAC0AZQBxACAAMAApACAAewAKACAAIAAgACAAYgByAGUAYQBrAAoAIAAgAH0ACgAgACAAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBNAGkAbABsAGkAcwBlAGMAbwBuAGQAcwAgADIAMAAwAAoAfQAgAHcAaABpAGwAZQAgACgAWwBEAGEAdABlAFQAaQBtAGUAXQA6ADoA"
!define MAVRODPI_LEGACY_SCRIPT_9 "VQB0AGMATgBvAHcAIAAtAGwAdAAgACQAZABlAGEAZABsAGkAbgBlACkACgAKAGkAZgAgACgAQAAoAEcAZQB0AC0ARQB4AGEAYwB0AEwAZQBnAGEAYwB5AFAAcgBvAGMAZQBzAHMAKQAuAEMAbwB1AG4AdAAgAC0AbgBlACAAMAApACAAewAKACAAIAB0AGgAcgBvAHcAIAAnAEwAZQBnAGEAYwB5ACAAZQBuAGcAaQBuAGUAIABpAHMAIABzAHQAaQBsAGwAIAByAHUAbgBuAGkAbgBnAC4AJwAKAH0ACgA="
!define MAVRODPI_LEGACY_BOOTSTRAP "JABiAD0AWwBzAHQAcgBpAG4AZwBdADoAOgBDAG8AbgBjAGEAdAAoACgAMQAuAC4AOQB8AEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAB7AFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEcAZQB0AEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGEAcgBpAGEAYgBsAGUAKAAoACcATQBBAFYAUgBPAEQAUABJAF8ATABFAEcAQQBDAFkAXwBTAEMAUgBJAFAAVABfACcAKwAkAF8AKQAsACcAUAByAG8AYwBlAHMAcwAnACkAfQApACkAOwAmACgAWwBTAGMAcgBpAHAAdABCAGwAbwBjAGsAXQA6ADoAQwByAGUAYQB0AGUAKABbAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBuAGkAYwBvAGQAZQAuAEcAZQB0AFMAdAByAGkAbgBnACgAWwBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAGIAKQApACkAKQA="

!macro NSIS_HOOK_PREINSTALL
  ; v0.2.4 did not own its foreground engine with a Job Object. During an
  ; updater install, terminate only the executable in this exact install path.
  ${If} $UpdateMode = 1
    ; NSIS exits successfully in silent mode when the main executable is still
    ; open, but it then skips replacing it. Close the known product process
    ; before touching files so an onarım really updates the installed binary.
    nsis_tauri_utils::FindProcess "${MAINBINARYNAME}.exe"
    Pop $R8
    ${If} $R8 = 0
      DetailPrint "Açık MavroDPI uygulaması güncelleme için kapatılıyor..."
      nsis_tauri_utils::KillProcess "${MAINBINARYNAME}.exe"
      Pop $R8
      Sleep 700
      nsis_tauri_utils::FindProcess "${MAINBINARYNAME}.exe"
      Pop $R8
      ${If} $R8 = 0
        StrCpy $R7 "Açık MavroDPI uygulaması kapatılamadı. Onarım dosyaları değiştirmeden durduruldu."
        DetailPrint "$R7"
        SetErrorLevel 1
        Abort
      ${EndIf}
    ${EndIf}

    ; Keep repair deterministic even when an older executable has a newer
    ; filesystem timestamp than the incoming release.
    SetOverwrite on
    StrCpy $R7 ""
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_ENGINE_PATH", w "$INSTDIR\resources\goodbyedpi\x86_64\goodbyedpi.exe") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Eski koruma motoru yolu hazırlanamadı."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_CIM_MODULE", w "$SYSDIR\WindowsPowerShell\v1.0\Modules\CimCmdlets\CimCmdlets.psd1") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güvenilir Windows CIM bileşeni hazırlanamadı."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}

    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_1", w "${MAVRODPI_LEGACY_SCRIPT_1}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (1)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_2", w "${MAVRODPI_LEGACY_SCRIPT_2}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (2)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_3", w "${MAVRODPI_LEGACY_SCRIPT_3}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (3)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_4", w "${MAVRODPI_LEGACY_SCRIPT_4}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (4)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_5", w "${MAVRODPI_LEGACY_SCRIPT_5}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (5)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_6", w "${MAVRODPI_LEGACY_SCRIPT_6}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (6)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_7", w "${MAVRODPI_LEGACY_SCRIPT_7}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (7)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_8", w "${MAVRODPI_LEGACY_SCRIPT_8}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (8)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_9", w "${MAVRODPI_LEGACY_SCRIPT_9}") i.r9'
    ${If} $R9 = 0
      StrCpy $R7 "Güncelleme temizleme adımı hazırlanamadı (9)."
      Goto mavrodpi_legacy_cleanup_env
    ${EndIf}

    DetailPrint "Önceki MavroDPI koruma motoru exact-path ile denetleniyor..."
    nsExec::ExecToLog '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand ${MAVRODPI_LEGACY_BOOTSTRAP}'
    Pop $R8
    ${If} $R8 != 0
      StrCpy $R7 "Önceki koruma motoru güvenli biçimde kapatılamadı (kod: $R8)."
    ${EndIf}

    mavrodpi_legacy_cleanup_env:
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_ENGINE_PATH", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_CIM_MODULE", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_1", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_2", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_3", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_4", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_5", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_6", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_7", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_8", p 0)'
    System::Call 'kernel32::SetEnvironmentVariableW(w "MAVRODPI_LEGACY_SCRIPT_9", p 0)'

    ${If} $R7 != ""
      DetailPrint "$R7"
      SetErrorLevel 1
      IfSilent mavrodpi_legacy_cleanup_abort 0
      MessageBox MB_ICONSTOP|MB_OK "$R7$\r$\nGüncelleme dosyaları değiştirilmeden durduruldu."
      mavrodpi_legacy_cleanup_abort:
      Abort
    ${EndIf}
  ${EndIf}
!macroend

!macro NSIS_HOOK_POSTINSTALL
  ; Tauri updater uygulama dosyalarını değiştirdikten sonra, kullanıcı daha
  ; önce otomatik servisi kurduysa yalnız eski/hash'i farklı payloadı onar.
  ${If} $UpdateMode = 1
    DetailPrint "MavroDPI Windows servisi güncel paketle doğrulanıyor..."
    nsExec::ExecToLog '"$INSTDIR\${MAINBINARYNAME}.exe" --repair-service-after-update'
    Pop $R8
    ${If} $R8 != 0
      DetailPrint "Windows servisi otomatik onarılamadı (kod: $R8). Uygulama Ayarlar bölümünde ONAR gösterecek."
    ${EndIf}
  ${EndIf}
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  ; Updater kurulumu mevcut servisi ve DNS durumunu korumalıdır.
  ${If} $UpdateMode <> 1
    DetailPrint "MavroDPI kapatılıyor..."
    nsis_tauri_utils::FindProcess "${MAINBINARYNAME}.exe"
    Pop $R8

    ${If} $R8 = 0
      nsis_tauri_utils::KillProcess "${MAINBINARYNAME}.exe"
      Pop $R8
      Sleep 500

      ${If} $R8 != 0
      ${AndIf} $R8 != 2
        StrCpy $R7 "MavroDPI kapatılamadı (kod: $R8)."
        Goto mavrodpi_cleanup_failed
      ${EndIf}

      nsis_tauri_utils::FindProcess "${MAINBINARYNAME}.exe"
      Pop $R8
      ${If} $R8 = 0
        StrCpy $R7 "MavroDPI işlemi kapatıldıktan sonra çalışmaya devam ediyor."
        Goto mavrodpi_cleanup_failed
      ${EndIf}
    ${EndIf}

    DetailPrint "MavroDPI ağ ayarları ve Windows servisi geri yükleniyor..."
    nsExec::ExecToLog '"$INSTDIR\${MAINBINARYNAME}.exe" --cleanup-before-uninstall'
    Pop $R8
    ${If} $R8 != 0
      StrCpy $R7 "Ağ ayarları veya Windows servisi geri yüklenemedi (kod: $R8)."
      Goto mavrodpi_cleanup_failed
    ${EndIf}
  ${EndIf}

  Goto mavrodpi_cleanup_done

  mavrodpi_cleanup_failed:
    DetailPrint "$R7"
    SetErrorLevel 1
    IfSilent mavrodpi_cleanup_abort 0
    MessageBox MB_ICONSTOP|MB_OK "$R7$\r$\nKaldırma işlemi sistem durumunu korumak için durduruldu."
  mavrodpi_cleanup_abort:
    Abort

  mavrodpi_cleanup_done:
!macroend

!macro NSIS_HOOK_POSTUNINSTALL
  ${If} $UpdateMode <> 1
    Delete "$DESKTOP\MavroDPI.lnk"
  ${EndIf}
!macroend
